on:
  push:
  pull_request:

name: test

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - github: 2.7
            tox: py27
            cmd: python
          - github: 3.6
            tox: py36
            cmd: python3
          - github: 3.7
            tox: py37
            cmd: python3
          - github: 3.8
            tox: py38
            cmd: python3
          - github: 3.9
            tox: py39
            cmd: python3
          - github: 3.10
            tox: py310
            cmd: python3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.version.github }}
      - run: |
          ${{ matrix.version.cmd }} -m pip install --upgrade pip
          ${{ matrix.version.cmd }} -m pip install tox
      - run: |
          tox -e ${{ matrix.version.tox }}-mylinux
