on:
  push:
  pull_request:
  workflow_dispatch:

name: test

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version:
          - github: 3.7
            tox: py37
            cmd: python3
          - github: 3.8
            tox: py38
            cmd: python3
          - github: 3.9
            tox: py39
            cmd: python3
          - github: "3.10"
            tox: py310
            cmd: python3
          - github: "3.11"
            tox: py311
            cmd: python3
          - github: "3.12"
            tox: py312
            cmd: python3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.version.github }}
      - run: |
          ${{ matrix.version.cmd }} -m pip install --upgrade pip
          ${{ matrix.version.cmd }} -m pip install tox
      - run: |
          tox -e ${{ matrix.version.tox }}-mylinux
